apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
spec:
  path: /catalog/services/applications/environments/${environment:-none}/external-dns/
  interval: ${external_dns_interval:-${kustomization_interval:-${global_interval:-5m}}}
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client