apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: "external-dns"
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: "5.1.0^"
      sourceRef:
        kind: HelmRepository
        name: ${external_dns_helm_repo:-bitnami}
        namespace: ${external_dns_helm_repo_ns:-flux-shared}
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values: 
    # global:
    #   imageRegistry: (( concat vars.settings.registry "docker.io"))
    rbac:
      create: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    txtPrefix: "extd."
    sources: [ "service", "ingress" ]
    triggerLoopOnEvent: true
    policy: "sync"
    registry: "txt" 
