apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: harvester
spec:
  path: /catalog/services/applications/environments/${environment:-none}/harvester/
  interval: ${harvester_dns_interval:-${kustomization_interval:-${global_interval:-5m}}}
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client