---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bedag-public
spec:
  interval: ${bedag_public_helm_repo_interval:-${helm_repo_interval:-${global_interval:-60m}}}
  url: https://bedag.github.io/helm-charts