---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cilium
spec:
  interval: ${cilium_helm_repo_interval:-${helm_repo_interval:-${global_interval:-60m}}}
  url: https://helm.cilium.io/