---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: ${grafana_helm_repo_interval:-${helm_repo_interval:-${global_interval:-60m}}}
  url: https://grafana.github.io/helm-charts