---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: harbor
spec:
  interval: ${harbor_helm_repo_interval:-${helm_repo_interval:-${global_interval:-60m}}}
  url: https://helm.goharbor.io