---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: longhorn
spec:
  interval: ${longhorn_helm_repo_interval:-${helm_repo_interval:-${global_interval:-60m}}}
  url: https://charts.longhorn.io