---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: minio
spec:
  interval: ${minio_helm_repo_interval:-${helm_repo_interval:-${global_interval:-60m}}}
  url: https://operator.min.io/