---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
spec:
  interval: ${prometheus_helm_repo_interval:-${helm_repo_interval:-${global_interval:-60m}}}
  url: https://prometheus-community.github.io/helm-charts