---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rancher
spec:
  interval: ${rancher_helm_repo_interval:-${helm_repo_interval:-${global_interval:-60m}}}
  url: https://releases.rancher.com/server-charts/latest