---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: shared-system
spec:
  targetNamespace: "shared-system"
  interval: 1m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client